variables:
  FLUTTER_DOCKER_IMAGE: cirrusci/flutter:2.3.0-24.0.pre

stages:
  - precheck
  - analyze
  - test
  - build
  - deploy
  - promote

commitlint:
  image:
    name: gtramontina/commitlint:8.3.5
    entrypoint: [ "" ]
  stage: precheck
  needs: [ ]
  script:
    - commitlint --from origin/master --verbose
  except:
    - master

stylelint:
  image: $FLUTTER_DOCKER_IMAGE
  stage: precheck
  needs: [ ]
  script:
    - flutter format --line-length 120 --dry-run --set-exit-if-changed .

analyze:
  image: $FLUTTER_DOCKER_IMAGE
  stage: analyze
  needs: [ ]
  script:
    - flutter analyze

test:
  image: $FLUTTER_DOCKER_IMAGE
  stage: test
  needs: [ ]
  before_script:
    - apt-get update
    - apt-get install -y libsqlite3-dev
  script:
    - flutter test --coverage
  after_script:
    - lcov --remove coverage/lcov.info lib/database.moor.dart --output-file coverage/lcov.info
    - genhtml --output ./coverage coverage/lcov.info
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'

build:debug:
  image: $FLUTTER_DOCKER_IMAGE
  stage: build
  needs: [ ]
  except:
    - master
    - tags
  script:
    - flutter build appbundle --debug

build:release:
  image: $FLUTTER_DOCKER_IMAGE
  stage: build
  needs: [ ]
  only:
    - master
    - tags
  before_script:
    - echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
    - echo -n "$SIGNING_JKS_FILE_BASE64" | base64 -d > android/app/upload-keystore.jks
    - if [ -n "$CI_COMMIT_TAG" ]; then BUILD_NAME=$CI_COMMIT_TAG; else BUILD_NAME=$CI_COMMIT_SHORT_SHA; fi
  script:
    - flutter build appbundle --release --build-number=$CI_PIPELINE_IID --build-name=$BUILD_NAME
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab

deploy:
  stage: deploy
  needs: [ "commitlint", "stylelint", "analyze", "build:release", "test" ]
  image: ruby:2.6.3
  only:
    - tags
  before_script:
    - echo "$GOOGLE_PLAY_API_KEY" > android/fastlane/google_play_api_key.json
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - gem install fastlane -NV
    - cd android
  script:
    - fastlane deploy
