variables:
  FLUTTER_DOCKER_IMAGE: cirrusci/flutter:2.2.1

stages:
  - precheck
  - analyze
  - build
  - deploy
  - promote

commitlint:
  image:
    name: gtramontina/commitlint:8.3.5
    entrypoint: [ "" ]
  stage: precheck
  needs: [ ]
  script:
    - commitlint --from origin/master --verbose
  except:
    - master

stylelint:
  image: $FLUTTER_DOCKER_IMAGE
  stage: precheck
  needs: [ ]
  script:
    - flutter format --dry-run --set-exit-if-changed .

analyze:
  image: $FLUTTER_DOCKER_IMAGE
  stage: analyze
  needs: [ ]
  script:
    - flutter analyze

build:
  image: $FLUTTER_DOCKER_IMAGE
  stage: build
  needs: [ ]
  before_script:
    - echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
    - echo -n "$SIGNING_JKS_FILE_BASE64" | base64 -d > android/app/upload-keystore.jks
    - if [ -n "$CI_COMMIT_TAG" ]; then BUILD_NAME=$CI_COMMIT_TAG; else BUILD_NAME=$CI_COMMIT_SHORT_SHA; fi
  script:
    - flutter build appbundle --build-number=$CI_PIPELINE_IID --build-name=$BUILD_NAME
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab

deploy:
  stage: deploy
  needs: [ "commitlint", "stylelint", "analyze", "build" ]
  image: ruby:2.6.3
  only:
    - tags
  before_script:
    - echo "$GOOGLE_PLAY_API_KEY" > android/fastlane/google_play_api_key.json
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - gem install fastlane -NV
    - cd android
  script:
    - fastlane deploy
