targets:
  $default:
    builders:
      moor_generator:
        enabled: false
      moor_generator|moor_generator_not_shared:
        enabled: true
        options:
          generate_connect_constructor: true
      mockito|mockBuilder:
        enabled: false

  run_built_value:
    dependencies: [ 'flauncher' ]
    builders:
      moor_generator:
        enabled: false
      moor_generator|preparing_builder:
        enabled: false