name: flauncher
description: Flutter-based Android TV launcher.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.5.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_remote_config: ^0.11.0
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  moor: ^4.5.0
  moor_inspector: ^0.3.1
  path_provider: ^2.0.5
  package_info_plus: ^1.0.6
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  sqlite3_flutter_libs: ^0.5.0
  unsplash_client: ^2.1.0
  webview_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  lints: ^1.0.1
  mockito: ^5.0.16
  moor_generator: ^4.5.1
  network_image_mock: ^2.0.1
  transparent_image: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
