name: flauncher
description: Flutter-based Android TV launcher.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.2.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  image_picker: ^0.7.5
  intl: ^0.17.0
  moor: ^4.3.2
  moor_inspector: ^0.2.0
  path_provider: ^2.0.1
  package_info_plus: ^1.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  lints: ^1.0.1
  mockito: ^5.0.10
  moor_generator: ^4.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
