name: flauncher
description: Flutter-based Android TV launcher.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.2.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  image_picker: ^0.7.5
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
